Template validation error message
ONSdigital/ssdc-rm-response-operations pull request #21
Opened 2021-09-27 13:00 UTC by LukeLoze1

# Motivation and Context
When server side validation fails we need to report on this in the correct manner

# What has changed
Reports back print template validation fails to the end user

# How to test?
Fire it up,  poke some bad validation at it like existing packcodes or templates like these [""].  I had to temp alter the java code to make an error for unknown supplier as the frontend limits this.

# Links
https://trello.com/c/2tuhw4KJ/2747-response-ops-create-template-validation-error-messages-are-not-being-passed-through-to-the-ui-5

# Screenshots (if appropriate):

2021-09-27 14:07 UTC, ryangrundy7 commented on .vscode/launch.json
> +}
Don't think you meant to push this?

2021-09-27 14:07 UTC, ryangrundy7 commented on build.sh
> +mvn clean install -Dmaven.test.skip=true
Needs to be back to mvn clean install

2021-09-28 06:37 UTC, LukeLoze1 commented on .vscode/launch.json
> +}
ta, will add to ignore

2021-09-28 08:27 UTC, NickGrantONS requested changes
Use `Optional` instead of returning `null` or a value

2021-09-28 12:20 UTC, ryangrundy7 approved these changes
Looks good 👍

2021-09-29 08:35 UTC, hbrace approved these changes

2021-09-29 09:21 UTC, NickGrantONS approved these changes

2021-09-29 09:33 UTC, merged