3037 rops rbac groups admin page
ONSdigital/ssdc-rm-response-operations pull request #51
Opened 2021-11-24 11:30 UTC by LukeLoze1

# Motivation and Context
add Group Member admin   to ROPS

# What has changed
Add new screens/code to achieve this

# How to test?
Setup some groups, members and admins in support tool.  Then view and try to remove them in this version of ROPS

# Links

# Screenshots (if appropriate):
](https://trello.com/b/yarvSxGu/generic-response-management)

2021-11-24 13:09 UTC, NickGrantONS commented on ui/src/DeleteUserFromGroupConfirmation.js
> +      {/* Todo How to do a cancel button? */}
Why is this TODO left here?

2021-11-24 13:10 UTC, NickGrantONS commented on ui/src/GroupAdmin.js
> +            <button onClick={() => openRemoveUserPage(groupUser)} type="button">
this button does not follow any government standards (GDS) or the ONS pattern library... it's just a completely unstyled plain HTML button.

2021-11-24 13:16 UTC, NickGrantONS commented on ui/src/GroupAdmin.js
> +      <Link to="/">← Back to home</Link>
Should go back to "my groups" not to home

2021-11-24 13:24 UTC, NickGrantONS requested changes
Problem summary:

1. Need to use government(GDS)/ONS UI standards... pattern library... can't just make things up or leave things unstyled
2. Every page needs a title, can't just have tables
3. Group details page should route back to the page it came from (i.e. "my groups" not home)
4. Table headings are for table headings. If you need to put other stuff on the screen those need to be their own UI elements... don't put everything into table headings because that's not accessible or good UI design
5. Only use the announcer to announce banners, not everything on the screen
6. See other comments

<img width="864" alt="Screenshot 2021-11-24 at 13 15 29" src="https://user-images.githubusercontent.com/41681172/143246245-8650d1be-be81-4ba3-b440-818de2e2532b.png">
Buttons not styled. Table header row has got other stuff in it which is nothing to do with table heading. No page heading. Back button should go back to "my groups".

<img width="859" alt="Screenshot 2021-11-24 at 13 14 37" src="https://user-images.githubusercontent.com/41681172/143246452-056f0010-4a01-4d86-8f88-da4407760033.png">
Table header row has got other stuff in it which is nothing to do with table heading. No page heading.

2021-11-25 10:01 UTC, AdamHawtin requested changes
The features seem to work fine but a few styling/wording points:
- Should have consistent capitalization on headings e.g. "Group Member email"
- The "remove" buttons on the user appear to be using the "call to action" style where they should probably just be plain buttons
- The yes and cancel buttons on the confirmation screen should use the grouped buttons styling so that the cancel button has the "secondary negative action" styling 
- Broken wording on the confirm user removal page e.g.  "Are you sure you wish to remove dummy@example.com user? from TEST GROUP"
- Slightly janky styling on the group table with the remove buttons floating out to the right of the table heading line

2021-11-25 14:41 UTC, AdamHawtin approved these changes
All seems to work as expected. 👍 

I'm not sure about the styling/placement of the "Back to ..."  buttons, especially when combined with a flashed message, but I think that's something to come back to with a site wide pattern for, especially since many existing pages are currently missing any form of back button entirely.

2021-11-26 10:09 UTC, NickGrantONS requested changes
Need to add description to table of groups and I think you should add it to the group user admin screen too. It will require API changes.

Or, we could say that because group description was added since originally tasking & sizing this ticket, it's beyond the scope... but it would be great to get it done.

Also, the "remove" button does look like a call to action, as Adam said... should be a secondary button, no?

2021-11-26 17:39 UTC, NickGrantONS requested changes
<img width="634" alt="Screenshot 2021-11-26 at 17 37 25" src="https://user-images.githubusercontent.com/41681172/143616033-4e3907cb-50ac-43d4-b01f-02975fffb0fa.png">

Table headings don't line up with table rows

<img width="697" alt="Screenshot 2021-11-26 at 17 38 14" src="https://user-images.githubusercontent.com/41681172/143616064-ef079b95-3ff2-4f0c-bd58-caf197d43179.png">

Remove button is still a massive "call to action" button, not a small grey secondary button

2021-11-29 11:06 UTC, NickGrantONS approved these changes
My comments have all been addressed. Great work. Looks good 👍

2021-11-29 11:37 UTC, merged