added print template endpoint
ONSdigital/ssdc-rm-response-operations pull request #6
Opened 2021-08-12 18:39 UTC by LukeLoze1

# Motivation and Context
New endpoint to get and create print templates

# What has changed
New endpoint and some test helper classes

# How to test?
use create to add some 

e.g. post:  http://localhost:7777/api/printtemplates
body
  {
      "packCode": "abc1",
       "template": ["hello", "world"],
      "printSupplier": "PrintSupplier2"
  }

Then use get to see if you can retrieve them

Get: http://localhost:7777/api/printtemplates

# Links
https://trello.com/c/OWzk3XOT/2629-rops-ui-second-feature-create-print-template-api-5

# Screenshots (if appropriate):

2021-08-16 12:34 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/ssdc/responseoperations/endpoint/PrintTemplateEndpoint.java
> +  private PrintTemplateDto mapPirntTemplates(PrintTemplate printTemplate) {
```suggestion
  private PrintTemplateDto mapPrintTemplates(PrintTemplate printTemplate) {
```

2021-08-16 12:36 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/ssdc/responseoperations/endpoint/PrintTemplateEndpoint.java
> +    printTemplate.setPrintSupplier(printTemplateDto.getPrintSupplier());
the print supplier is not being validated. It needs to be checked against the print supplier config. See how Support Tool's API does it here: https://github.com/ONSdigital/ssdc-rm-support-tool/blob/3c8c65dbee7be38789452b82c5f9a4512c0a4211/src/main/java/uk/gov/ons/ssdc/supporttool/endpoint/PrintSuppliers.java#L44

2021-08-16 12:37 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/ssdc/responseoperations/endpoint/PrintTemplateEndpoint.java
> +    return printTemplates.stream().map(this::mapPirntTemplates).collect(Collectors.toList());
```suggestion
    return printTemplates.stream().map(this::mapPrintTemplates).collect(Collectors.toList());
```

2021-08-16 12:39 UTC, NickGrantONS requested changes
Needs to validate print supplier against configured suppliers

2021-08-17 08:51 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/ssdc/responseoperations/endpoint/PrintTemplateEndpoint.java
> +      return new ResponseEntity(HttpStatus.BAD_REQUEST);
why doesn't the `checkPrintSupplierValid` method just throw the exception... it lives inside the Endpoint class anywawy

2021-08-18 08:00 UTC, NickGrantONS requested changes
Sorry... another couple of validations needed: pack code can't be blank/null. Also, obviously there must be a minimum of one non-blank/null item in the template array... indeed every item in the array must not be blank/null, and there has to be one item for it to be a meaningful/useful template

2021-08-19 15:39 UTC, NickGrantONS approved these changes

2021-08-23 07:54 UTC, liamtoozer approved these changes
LGTM 👍

2021-08-23 08:34 UTC, merged