case insensitive checking
ONSdigital/ssdc-rm-response-operations pull request #88
Opened 2022-03-21 08:44 UTC by LukeLoze1

# Motivation and Context
Shouldn't be case sensitive adding emails

# What has changed
makes it case insensitive

# How to test?
Try to add a user to a group, manually change value in text box to change the case of some letters.  Check that the email it adds still correct (in this case it will use the capitalization/case already stored for the email

# Links
[

](https://trello.com/c/IQ5b0zYl/3309-defect-adding-user-emails-in-support-tool-is-case-sensitive-5)

# Screenshots (if appropriate):

2022-03-21 13:48 UTC, liamtoozer commented on ui/src/AddUserToGroup.js
> +    return false;
```suggestion
    return location.state.existingEmailsInGroup.filter(
        (existingEmail) =>
            existingEmail.toLowerCase() === newEmail.toLowerCase()
    ).length > 0;
```

2022-03-21 13:48 UTC, liamtoozer approved these changes
LGTM 👍  Tested locally

2022-03-21 16:25 UTC, ryangrundy7 approved these changes

2022-03-22 08:01 UTC, AdamHawtin requested changes
I think the backend also needs updating, the user look-ups there must also be case-insensitive.

2022-03-23 09:20 UTC, AdamHawtin approved these changes
LGTM

2022-03-23 09:25 UTC, merged